"""
Unit tests for the Audit context.

The service depends only on the ``AuditLogRepository`` port, so it runs against
an in-memory fake — no Mongo. The decorator is tested with a patched recorder.
"""
from __future__ import annotations

from unittest.mock import patch

from django.test import SimpleTestCase
from rest_framework.response import Response

from auditoria.application.services import AuditService, record_event
from auditoria.domain.entities import AuditAction, AuditLog
from auditoria.domain.ports import AuditLogFilter, AuditLogRepository
from auditoria.infrastructure.context import (
    AuditContext,
    clear_context,
    set_context,
)
from auditoria.interfaces.decorators import audit_action, resolve_admin_id
from auditoria.interfaces.middleware import _infer_module


class FakeAuditRepository(AuditLogRepository):
    def __init__(self) -> None:
        self.saved: list[AuditLog] = []

    def save(self, log: AuditLog) -> None:
        self.saved.append(log)

    def query(self, criteria: AuditLogFilter) -> tuple[list[dict], int]:
        self.criteria = criteria
        return [{"id": "1"}], 1


class _FakeToken(dict):
    """Mimics a simple-jwt validated token (dict-like with .get)."""


class _FakeRequest:
    def __init__(self, *, auth=None, user=None) -> None:  # noqa: ANN001
        self.auth = auth
        self.user = user


class AuditLogEntityTests(SimpleTestCase):
    def test_to_document_has_exact_schema(self) -> None:
        log = AuditLog(admin_id="a1", accion="login", modulo="auth")
        doc = log.to_document()
        self.assertEqual(
            set(doc.keys()),
            {"id", "admin_id", "accion", "modulo", "entidad", "entidad_id",
             "ip", "user_agent", "metadata", "fecha"},
        )

    def test_id_and_fecha_autogenerated(self) -> None:
        log = AuditLog(admin_id="a1", accion="login", modulo="auth")
        self.assertTrue(log.id)
        self.assertIsNotNone(log.fecha)


class AuditServiceTests(SimpleTestCase):
    def test_record_persists_log(self) -> None:
        repo = FakeAuditRepository()
        AuditService(repo).record(admin_id="a1", accion="bloqueo", modulo="users",
                                   entidad="user", entidad_id="9")
        self.assertEqual(repo.saved[0].entidad_id, "9")
        self.assertEqual(repo.saved[0].accion, "bloqueo")

    def test_query_forwards_criteria(self) -> None:
        repo = FakeAuditRepository()
        results, total = AuditService(repo).query(AuditLogFilter(modulo="users"))
        self.assertEqual(total, 1)
        self.assertEqual(repo.criteria.modulo, "users")


class RecordEventTests(SimpleTestCase):
    def setUp(self) -> None:
        set_context(AuditContext(ip="1.2.3.4", user_agent="UA", request_id="rid"))
        self.addCleanup(clear_context)

    def test_enriches_from_context(self) -> None:
        repo = FakeAuditRepository()
        record_event(admin_id="a1", accion=AuditAction.APPROVE, modulo="technicians",
                     repository=repo)
        log = repo.saved[0]
        self.assertEqual(log.ip, "1.2.3.4")
        self.assertEqual(log.user_agent, "UA")
        self.assertEqual(log.metadata["request_id"], "rid")
        self.assertEqual(log.accion, "aprobacion")

    def test_admin_id_falls_back_to_anonymous(self) -> None:
        repo = FakeAuditRepository()
        record_event(admin_id=None, accion="x", modulo="m", repository=repo)
        self.assertEqual(repo.saved[0].admin_id, "anonymous")

    def test_swallows_repository_errors(self) -> None:
        class Broken(AuditLogRepository):
            def save(self, log: AuditLog) -> None:
                raise RuntimeError("mongo down")

            def query(self, criteria: AuditLogFilter):
                raise RuntimeError

        # Must not raise.
        record_event(admin_id="a1", accion="x", modulo="m", repository=Broken())


class ResolveAdminIdTests(SimpleTestCase):
    def test_prefers_token_claim(self) -> None:
        req = _FakeRequest(auth=_FakeToken(user_id="claim-1"))
        self.assertEqual(resolve_admin_id(req), "claim-1")

    def test_falls_back_to_user_id(self) -> None:
        class U:
            id = 42
        self.assertEqual(resolve_admin_id(_FakeRequest(user=U())), "42")

    def test_none_when_anonymous(self) -> None:
        self.assertIsNone(resolve_admin_id(_FakeRequest()))


class DecoratorTests(SimpleTestCase):
    def setUp(self) -> None:
        set_context(AuditContext())
        self.addCleanup(clear_context)

    def _make_view(self, response):  # noqa: ANN001
        class View:
            @audit_action(AuditAction.BLOCK, modulo="users", entidad="user")
            def patch(self, request, user_id):  # noqa: ANN001
                return response
        return View()

    def test_records_on_success(self) -> None:
        request = _FakeRequest(auth=_FakeToken(user_id="a1"))
        with patch("auditoria.interfaces.decorators.record_event") as rec:
            view = self._make_view(Response(status=200))
            view.patch(request, user_id="9")
        rec.assert_called_once()
        kwargs = rec.call_args.kwargs
        self.assertEqual(kwargs["accion"], AuditAction.BLOCK)
        self.assertEqual(kwargs["entidad_id"], "9")
        self.assertTrue(request._audit_recorded)

    def test_does_not_record_on_failure(self) -> None:
        request = _FakeRequest(auth=_FakeToken(user_id="a1"))
        with patch("auditoria.interfaces.decorators.record_event") as rec:
            view = self._make_view(Response(status=409))
            view.patch(request, user_id="9")
        rec.assert_not_called()


class InferModuleTests(SimpleTestCase):
    def test_admin_path(self) -> None:
        self.assertEqual(_infer_module("/api/admin/users/5/ban/"), "users")

    def test_dashboard_path(self) -> None:
        self.assertEqual(_infer_module("/api/dashboard/summary/"), "summary")

    def test_v1_path(self) -> None:
        self.assertEqual(_infer_module("/api/v1/services/"), "services")
